<a href="https://colab.research.google.com/github/Jagwork1923/JagadishAI/blob/main/Assignment_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

In [2]:
#1 Load the Dataset
#make sure the filename matches exactly
df = pd.read_csv('FinalData.csv')

In [3]:
#2. Inspect the Data
print("---Data Information---")
print(df.info())
print('\n---Missing Values---')
print(df.isnull().sum())

---Data Information---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Age     400 non-null    float64
 1   Bp      400 non-null    float64
 2   Sg      400 non-null    float64
 3   Al      400 non-null    float64
 4   Su      400 non-null    float64
 5   Rbc     400 non-null    float64
 6   Pc      400 non-null    float64
 7   Pcc     400 non-null    float64
 8   Ba      400 non-null    float64
 9   Bgr     400 non-null    float64
 10  Bu      400 non-null    float64
 11  Sc      400 non-null    float64
 12  Sod     400 non-null    float64
 13  Pot     400 non-null    float64
 14  Hemo    400 non-null    float64
 15  Pcv     400 non-null    float64
 16  Wbcc    400 non-null    float64
 17  Rbcc    400 non-null    float64
 18  Htn     400 non-null    float64
 19  Dm      400 non-null    int64  
 20  Cad     400 non-null    float64
 21  Appet   400 non-

In [4]:
#3. Handle Missing Values
# This fills missing numbers with the average (mean)
imputer = SimpleImputer(strategy='mean')
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = imputer.fit_transform(df[numeric_cols])

In [6]:
#4.Encode Categorical Data
#Converts text categories into numbers (e.g., 'Yes/no' to 0/1)
le = LabelEncoder()
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

TypeError: data type 'objects' not understood

### 5. Feature Scaling
Many machine learning algorithms perform better when numerical input variables are scaled to a standard range. Here, we'll use `StandardScaler` to transform our numerical features so they have a mean of 0 and a standard deviation of 1.

In [7]:
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("---Data after scaling (first 5 rows)---")
display(df.head())

---Data after scaling (first 5 rows)---


,Age,Bp,Sg,Al,Su,Rbc,Pc,Pcc,Ba,Bgr,Bu,Sc,Sod,Pot,Hemo,Pcv,Wbcc,Rbcc,Htn,Dm,Cad,Appet,pe,Ane,Class
0,-0.205459,0.262336,0.421486,-0.013614,-0.437780,-0.000972,0.593248,-0.346311,-0.243952,-0.361993,-0.435272,-0.333725,0.000106,0.000763,1.059100,0.628470,-0.240518,0.585900,1.309979,1.385535,-0.306474,0.509266,-0.485676,-0.421227,0.774597
1,-2.623805,-1.966582,0.421486,2.347239,-0.437780,-0.000972,0.593248,-0.346311,-0.243952,0.000042,-0.800945,-0.405020,0.000106,0.000763,-0.452268,-0.108551,-0.954786,0.002055,-0.767210,-0.721743,-0.306474,0.509266,-0.485676,-0.421227,0.774597
2,0.620318,0.262336,-1.421074,0.773337,2.479942,0.614718,0.593248,-0.346311,-0.243952,3.681436,-0.089914,-0.226782,0.000106,0.000763,-1.078932,-0.968408,-0.359563,0.002055,-0.767210,1.385535,-0.306474,-1.968612,-0.485676,2.379952,0.774597
3,-0.205459,-0.480637,-2.342354,2.347239,-0.437780,0.614718,-2.015870,2.917695,-0.243952,-0.415548,-0.028968,0.129695,-2.885860,-0.755560,-0.489130,-0.845571,-0.677015,-0.963076,1.309979,-0.721743,-0.306474,-1.968612,2.064138,2.379952,0.774597
4,-0.028507,0.262336,-1.421074,0.773337,-0.437780,0.614718,0.593248,-0.346311,-0.243952,-0.562825,-0.638424,-0.298077,0.000106,0.000763,-0.341680,-0.477061,-0.438926,-0.129012,-0.767210,-0.721743,-0.306474,0.509266,-0.485676,-0.421227,0.774597


In [8]:
#5. Split Features (X) and Target (Y)
#Assuming the last column is what you want to predict
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values

In [9]:
X

array([[-0.20545916,  0.26233629,  0.4214856 , ...,  0.50926576,
        -0.48567569, -0.4212274 ],
       [-2.62380543, -1.96658231,  0.4214856 , ...,  0.50926576,
        -0.48567569, -0.4212274 ],
       [ 0.62031762,  0.26233629, -1.4210744 , ..., -1.96861167,
        -0.48567569,  2.37995229],
       ...,
       [-2.32888515,  0.26233629,  0.4214856 , ...,  0.50926576,
        -0.48567569, -0.4212274 ],
       [-2.03396488, -1.22360944,  1.3427656 , ...,  0.50926576,
        -0.48567569, -0.4212274 ],
       [ 0.38438139,  0.26233629,  1.3427656 , ...,  0.50926576,
        -0.48567569, -0.4212274 ]])

In [10]:
Y

array([ 0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77459667,
        0.77459667,  0.77459667,  0.77459667,  0.77459667,  0.77

In [12]:
#6. Split into Training and Testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=43)

In [13]:
X

array([[-0.20545916,  0.26233629,  0.4214856 , ...,  0.50926576,
        -0.48567569, -0.4212274 ],
       [-2.62380543, -1.96658231,  0.4214856 , ...,  0.50926576,
        -0.48567569, -0.4212274 ],
       [ 0.62031762,  0.26233629, -1.4210744 , ..., -1.96861167,
        -0.48567569,  2.37995229],
       ...,
       [-2.32888515,  0.26233629,  0.4214856 , ...,  0.50926576,
        -0.48567569, -0.4212274 ],
       [-2.03396488, -1.22360944,  1.3427656 , ...,  0.50926576,
        -0.48567569, -0.4212274 ],
       [ 0.38438139,  0.26233629,  1.3427656 , ...,  0.50926576,
        -0.48567569, -0.4212274 ]])

In [14]:
#Feature Scaling
#This puts all numbers on a similar scale(e.g., -1 to 1)
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [15]:
print("\npreprocessing Complete!")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")


preprocessing Complete!
X_train shape: (320, 24)
X_test shape: (80, 24)


In [18]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix

In [19]:
#1. Initialize the model
classifier = RandomForestRegressor(n_estimators=100, random_state=42)

In [20]:
#Train the model using the scaled training data
classifier.fit(X_train, Y_train)

RandomForestRegressor(random_state=42)

In [21]:
#3. Predict the results for the Test set
y_pred = classifier.predict(X_test)

In [23]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix

# Get the unique scaled class values from Y_test
un_scaled_classes = np.unique(Y_test)

# Assume the smaller scaled value maps to class 0 and the larger to class 1
# This relies on the original 'Class' column being 0 and 1, and StandardScaler maintaining order
class_0_scaled = np.min(un_scaled_classes)
class_1_scaled = np.max(un_scaled_classes)

# Create discrete versions of Y_test (true labels)
Y_test_discrete = np.where(Y_test == class_0_scaled, 0, 1)

# For y_pred (continuous predictions), use a threshold to convert to discrete classes
# The midpoint between the two scaled class values is a reasonable threshold
midpoint = (class_0_scaled + class_1_scaled) / 2
y_pred_discrete = np.where(y_pred >= midpoint, 1, 0)

# Now, evaluate the performance using the discrete labels
accuracy = accuracy_score(Y_test_discrete, y_pred_discrete)
print(f"Model Accuracy: {accuracy * 100:.2f}%")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test_discrete, y_pred_discrete))

Model Accuracy: 96.25%

Confusion Matrix:
[[34  0]
 [ 3 43]]
